pipeline {
    agent any
    environment {

        APP_DOCKER_REGISTRY = "localhost:5000"

        APP_POM_PATH = 'app/pom.xml'

        APP_PROJECT_NAME = 'testjenkins'
        APP_PROJECT_PATH = ""
        APP_PROFILE = "dev"
        APP_PORT = 8081
        APP_NODEPORT = 30001
        APP_DOCKERFILE = "app/deploy/Dockerfile"
        APP_DOCKER_CONTEXT = "app"
        APP_REPLICAS = 1
    }
    stages {
        stage('Clone app repository') {
            steps {
                dir('app') {
                    checkout([
                        $class: 'GitSCM', 
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[url: 'https://github.com/psantiagomm/testjenkins.git']]
                    ])
                }
            }
        }
        stage('Load Reusable Stages') {
            steps {
                script {
                    stages = load './deploy/scripts/groovy/deployStages.groovy'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    stages.defineEnvVars()
                    stages.buildStage()                    
                }
            }
        }
        stage('Push Docker Image') {          
            steps {
                script {
                    stages.pushStage()
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                        stages.deployStage()
                }
            }
        }
    }
    post {
        success {
            echo 'Deploy completed successfully!'
        }
        failure {
            echo 'Deploy failed!'
        }
    }
}