pipeline {
    agent any
    environment {

        APP_DOCKER_REGISTRY = "localhost:5000"

        APP_POM_PATH = 'app/pom.xml'

        APP_PROJECT_NAME = 'testjenkins'
        APP_KUBE_NAMESPACE = "qa"
        APP_PROFILE = "qa"
        APP_PORT = 8082
        APP_NODEPORT = 30002
        APP_DOCKERFILE = "app/deploy/Dockerfile"
        APP_DOCKER_CONTEXT = "app"
        APP_REPLICAS = 1
        APP_MASTER_PASS_CREDENTIAL_ID = "MYAPP_MATER_PASS"
    }
    stages {
        stage('Clone app repository') {
            steps {
                dir('app') {
                    checkout([
                        $class: 'GitSCM', 
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[url: 'https://github.com/psantiagomm/testjenkins.git']]
                    ])
                }
            }
        }
        stage('Load Reusable Stages') {
            steps {
                script {
                    stages = load './deploy/scripts/groovy/onlyDeployStages.groovy'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    stages.deployStage()
                }
            }
        }
    }
    post {
        success {
            echo 'Deploy completed successfully!'
        }
        failure {
            echo 'Deploy failed!'
        }
    }
}