pipeline {
    agent any
    environment {

        // APP_DOCKER_REGISTRY = "localhost:5000"

        APP_POM_PATH = 'app/collectionapi/pom.xml'

        APP_PROJECT_NAME = 'collectionapi'
        APP_KUBE_NAMESPACE = "default"
        APP_PROFILE = "dev"
        APP_PORT = 8081
        APP_NODEPORT = 30001
        APP_DOCKERFILE = "app/collectionapi/deploy/Dockerfile"
        APP_DOCKER_CONTEXT = "app/collectionapi"
        APP_REPLICAS = 1
        APP_MASTER_PASS_CREDENTIAL_ID = "COLLECTIONAPI_MATER_PASS"
    }
    stages {
        stage('Clone app repository') {
            steps {
                dir('app') {
                    checkout([
                        $class: 'GitSCM', 
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[url: 'http://10.100.82.76:9003/Indra-T1/gatewayfixed/collect.git', credentialsId: 'SANTIAGO_GIT_TIGO' ]]
                    ])
                }
            }
        }
        stage('Load Reusable Stages') {
            steps {
                script {
                    stages = load './deploy/scripts/groovy/deployStages.groovy'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    stages.buildStage()                    
                }
            }
        }
        stage('Push Docker Image') {          
            steps {
                script {
                    stages.pushStage()
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                        stages.deployStage()
                }
            }
        }
    }
    post {
        success {
            echo 'Deploy completed successfully!'
        }
        failure {
            echo 'Deploy failed!'
        }
    }
}